line-length = 79
indent-width = 4

[lint]
# See here for more information on rule codes:
# https://docs.astral.sh/ruff/rules/
select = ["ARG", "B", "C4", "E", "F", "I", "N", "PL", "UP", "SIM", "W"]

[lint.pycodestyle]
max-doc-length = 72

[lint.pydocstyle]
convention = "google"
